# -*- coding: utf-8 -*-

from app import app
from flask import render_template
from models import Post

@app.route('/')
def index():
	first_post = Post('Direction','Katherine','What is the sound you cannot hear, in the coldness of the night.What is the feeling you crave to have, far beyond your sight.What is there now behind horizons, where you have never been.Does it hold a perfect face, or the same old thing again.Why were you even put here at all?, and when will you meet your fate?And are you going to make a difference...before it is too late.I think Im starting...and hope to see the day Im waiting for.hen Wire is finally removed from me...And Peace is forever More.')
	second_post = Post('Spirits Almost Gone','Kitty Lee','Please break me down So I cant get up I need to wear this frown And drink blood from this cup I need to learn the lesson I have been presented In order to be pround And not be resented But I dont know the answer To the question proposed So will somebody help me And show this spirit arose? For I have fallen deep And this cut has bruised my soul This is why I weep And lose all gained control For without I dont know What I am to do Where I am to go Or what pain to be put threw To face another heart break? I think Id rather not.. I wouldnt risk the chance Of another getting caught Cause that first time it broke me The second Im ripped apart Now I cannot see And Im left with a broken heart So please tell me why I choose to live on When I wanna die And my spirits almost gone?')
	third_post = Post('Apply Gentleness to Everything', 'Katherine', 'Apply Gentleness To Everything Throughout life we must cope with blockages that impede our forward momentum. Whether these obstacles are of a personal, professional, or societal nature, our first instinct may be to push against the obstruction. But the simplest way to alleviate resistance is to approach it gently, with a soft manner and kind intentions. Struggle and strife can find no foothold when confronted with mildness because conflict can only exist when fed by two opposing forces. So many areas of our lives can benefit from the application of gentleness. The beauty of gentleness lies in its multifaceted nature. It is part love, part compassion, part patience, part understanding, and part respect for others. When we move through life gently as a matter of course, we naturally attract these wonderful elements into our lives.This does not mean that gentle people are by nature passive or meek. Rather, their copious inner power is manifested in their gentleness and their choice to move with the flow of the universe instead of against it. You can make use of gentleness in your own life by applying it in situations where you feel challenged by your circumstances or by people in your environment. As you move forward gently, the energy pervading your life will likely shift and, consequently, the blockages before you will vanish. Cooperation progresses smoothly when approached gently because all parties involved feel confident that their needs will be met. And quarrels are easily quelled with gentleness because the dualistic concepts of losing and winning are made moot by our willingness to exercise infinite patience with those whose values differ from our own. Gentleness must be practiced, as we are inadvertently encouraged to act competitive in certain phases of our lives. At first, your established habits may make being truly gentle challenging. Yet after a time, if you commit to consciously applying gentleness to all areas of your life, whether by collaborating rather than competing or yielding graciously to the impassable roadblocks in your path in order to seek a new road, you will find that you begin to act gently habitually. Your patterns of thought and behavior become ever more peaceful, and you will discover that you encounter far less impassable resistance on your individual journey.')
	fourth_post = Post('Arrow of Love', 'Kitty Lee', 'The arrow of Love Shot by Cupid Not just to bring true lovee But to test it aswell To feel the pain of the arrow As the love you feel is not as strong Become Struck with the arrow With your love of your life You will find true love The love to numb and ignore the pain of the piercing arrow. However true love is rare Making it so valuable Often misinterpreted and decieved With Cupids arrow The love and pain will always stay in you Without pain brings you love Lose the love And you gain back the pain. A bleeding heart some call itWhen not a blade But a unreal yet so real object penetrating your heart penetrated your emotions Attempt pulling it out alone Results in failure To confront pain Two must aid one another For love starts with two And so should end with two. so is true love really worthe such a great risk? Always..')
	fifth_post = Post('Quill', 'Katherine', 'Tightly grip the quill, Puncture the wrist, Sign your name on the dotted line, Appease the devils wish. Or stand up and fight, Pull out the fiery sword, Pick up the shield of life, Fend off the devils hordes. The first path is simplest, Living with ease on earth, But the perpetuity after death, Is infinitely without mirth. The second is futile at best, Much blood exuded by self and foes, Though the post-demise eternity, A tranquil entity will pose.')

	return render_template("Index.html", posts = [first_post, second_post, third_post, fourth_post, fifth_post])
